# Generated by Django 4.2 on 2023-10-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=1)),
                ('age', models.IntegerField()),
                ('education_years', models.IntegerField()),
                ('socioeconomic_status', models.FloatField()),
                ('mmse', models.FloatField()),
                ('cdr', models.FloatField()),
                ('etiv', models.IntegerField()),
                ('nwbv', models.FloatField()),
                ('asf', models.FloatField()),
                ('predicted_category', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
