# Generated by Django 4.2 on 2023-10-28 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdata',
            name='predicted_category',
        ),
    ]
