# Generated by Django 4.2 on 2023-10-29 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_patientdata_predicted_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdata',
            name='predicted_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
